# Generated by Django 5.1.7 on 2025-04-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingarea',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
